const development = [
    {
      id: "1",
      image: "/Images/web developer full.png",
      title: "faizan sohail tariq",
      description: "Become a certified full stack web developer",
      Price: "70,000 PKR",
      Duration:"6 months",
      Skilllevel:"Intermediate",
    },
    {
      id: "2",
      image: "/Images/web designer.png",
      title: "faizan sohail tariq",
      description: "Become a certified  web designer & developer",
      Price: "25,000 PKR",
      Duration:"2 months",
      Skilllevel:"Intermediate",
    },
    {
      id: "3",
      image: "/Images/full java developer.jpeg",
      title: "faizan sohail tariq",
      description: "Become a certified javaScript  web developer",
      Price: "40,000 PKR",
      Duration:"4 months",
      Skilllevel:"Intermediate",
    },
    {
      id: "4",
      image: "/Images/front-end developr.jpeg",
      title: "faizan sohail tariq",
      description: "Become a certified front end developer",
      Price: "25,000 PKR",
      Duration:"2.5 months",
      Skilllevel:"Intermediate",
    },
    {
      id: "5",
      image: "/Images/laravel developer.png",
      title: "faizan sohail tariq",
      description: "Become a certified laravel  developer ",
      Price: "25,000 PKR",
      Duration:"2 months",
      Skilllevel:"Intermediate",
    },
    {
        id: "6",
        image: "/Images/python developer.png",
        title: "faizan sohail tariq",
        description: "python programming with django framework",
        Price: "20,000 PKR",
        Duration:"3 months",
        Skilllevel:"Intermediate",
      },
      {
        id: "7",
        image: "/Images/android developre.png",
        title: "Ahtisham-ul-haq",
        description: "become an android application developer",
        Price: "20,000 PKR",
        Duration:"2.5 months",
        Skilllevel:"Intermediate",
      },  
      {
        id: "8",
        image: "/Images/wordpress developer.png",
        title: "faizan sohail tariq",
        description: "Wordpress Full customization development",
        Price: "20,000 PKR",
        Duration:"1 months",
        Skilllevel:"Intermediate",
      },
      {
        id: "9",
        image: "/Images/ruby on rails.png",
        title: "faizan sohail tariq",
        description: "Become a ruby on rails web developer",
        Price: "23,000 PKR",
        Duration:"2 months",
        Skilllevel:"Intermediate",
      },
      {
        id: "10",
        image: "/Images/mean stack development.png",
        title: "faizan sohail tariq",
        description: "Become a certified mean stack developer",
        Price: "27,000 PKR",
        Duration:"6 months",
        Skilllevel:"Intermediate",
      },
      {
        id: "11",
        image: "/Images/react developer.png",
        title: "Taimoor Rasheed",
        description: "Become a certified React js developer",
        Price: "25,000 PKR",
        Duration:"2 months",
        Skilllevel:"Intermediate",
      },
      {
        id: "12",
        image: "/Images/programming expert.png",
        title: "faizan sohail tariq",
        description: "Become a certified programming expert",
        Price: "20,000 PKR",
        Duration:"4 months",
        Skilllevel:"Intermediate",
      },
  ];
export default development