const marketingdata = [
    {
      id: "1",
      image: "/Images/DIGITAL MEDIA.jpg",
      title: "Sehab Razzaq",
      description: "Become a digital media marketing expert",
      Price: "60,000",
      Duration:"6 months",
      Skilllevel:"Intermediate",
    },
    {
      id: "2",
      image: "/Images/SOCIAL MEADIA MARKETING.jpg",
      title: "Sehab Razzaq",
      description: "Become a social media marketing expert",
      Price: "20,000",
      Duration:"3 months",
      Skilllevel:"Intermediate",
    },
    {
      id: "3",
      image: "/Images/FREELANCING.jpg",
      title: "Mahru-n-Nisa",
      description: "Become an expert freelancer course ",
      Price: "13,000",
      Duration:"2 months",
      Skilllevel:"Intermediate",
    },
    {
      id: "4",
      image: "/Images/SEO AND SEM.jpg",
      title: "Ezzaz naseer",
      description: "Become an expert in seo sem wordpress",
      Price: "20,000",
      Duration:"4 months",
      Skilllevel:"Intermediate",
    },
    {
      id: "5",
      image: "/Images/YOUTUBE STAR.jpg",
      title: "Fatima Iqbal",
      description: "Become a youtube star and earn money",
      Price: "13,000",
      Duration:"4 months",
      Skilllevel:"Intermediate",
    },
    {
        id: "6",
        image: "/Images/FACEBOOK AND INSTA.jpg",
        title: "Aqsa Razzaq",
        description: "Learn facebook and instagram marketing ",
        Price: "23,000",
        Duration:"2 months",
        Skilllevel:"Intermediate",
      },
      {
        id: "7",
        image: "/Images/CONTENT WRITING.jpg",
        title: "Maham Khan",
        description: "Become an expert content writer in course",
        Price: "13,000",
        Duration:"1.5 months",
        Skilllevel:"Intermediate",
      },
      {
        id: "8",
        image: "/Images/TIKTOK.jpeg",
        title: "Aqsa Razzaq",
        description: "Grow your bussiness with your tiktok shop ",
        Price: "10,000",
        Duration:"1 months",
        Skilllevel:"Intermediate",
      },
      {
        id: "9",
        image: "/Images/SOCIAL MEADIA MARKETING.jpg",
        title: "Fatima Iqbal",
        description: "Become a social media marketing expert",
        Price: "20,000",
        Duration:"2 months",
        Skilllevel:"Intermediate",
      },
  ];
  export default marketingdata;
  